### ISSUE TITLE
Linux startup issue

### ISSUE THREAD

**Issue by mpj17** [green0range/timetables#13]
I have a start-up issue with Ubuntu 22.04.1 (GNOME 42.4 under Wayland)

```console
$ ./Timetables 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "main.py", line 1354, in <module>
  File "main.py", line 45, in __init__
  File "sound.py", line 24, in __init__
  File "pydub/audio_segment.py", line 796, in from_mp3
  File "pydub/audio_segment.py", line 728, in from_file
  File "pydub/utils.py", line 279, in mediainfo_json
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[20853] Failed to execute script 'main' due to unhandled exception!
```

It looks as if *Timetables* is trying to use `pydub` to convert an MP3 to a WAV. As part of this`pydb` is trying get some metadata about the file in JSON format using `ffprobe`. It is failing when trying to decode the JSON output from `ffprobe`. At a guess a file name of the MP3 file is wrong, and it is only in the dark recesses of the pipe within `pydub` that this is being caught?

For what it is worth, I do have `ffmpeg` installed
```console
$ ffmpeg --version
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
```

**Comment by green0range** [comment]
Your right, if it can't find a WAV file, it looks for the MP3 version and converts it into WAV using `pydub`. This should happen once on the first run after download, as MP3 is used for the download due to smaller file size. I don't know why this fails for you. I've added extra checks on the file name in 0dfee0fa1a1a76b2c1909b232fffd19ccbc8ae1d but I don't think this will help as the checks pass every time for me. I've also added a work around: you can disable music by editing `assets/music/music_data.json` and changing the `enable_music` flag to `false`. Note that this will only fix your issue with the 0dfee0fa1a1a76b2c1909b232fffd19ccbc8ae1d code because earlier code still attempts to do the conversion even if music is disabled, it just doesn't play the converted files.

**Comment by green0range** [comment]
Didn't mean to close sorry, this is still an issue. Last comment only a workaround
